


export const CREATE_NEW_POST_REQUEST = "CREATE_NEW_POST_REQUEST";
export const CREATE_NEW_POST_SUCCESS = "CREATE_NEW_POST_SUCCESS";
export const CREATE_NEW_POST_FAIL = "CREATE_NEW_POST_FAIL";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAIL = "EDIT_POST_FAIL";

export const GET_A_POST_REQUEST = "GET_A_POST_REQUEST";
export const GET_A_POST_SUCCESS = "GET_A_POST_SUCCESS";
export const GET_A_POST_FAIL = "GET_A_POST_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const POST_IMAGE_UPLOAD_REQUEST = "POST_IMAGE_UPLOAD_REQUEST";
export const POST_IMAGE_UPLOAD_SUCCESS = "POST_IMAGE_UPLOAD_SUCCESS";
export const POST_IMAGE_UPLOAD_FAIL = "POST_IMAGE_UPLOAD_FAIL";
