export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";


export const USER_PUBLISH_REQUEST = "USER_PUBLISH_REQUEST";
export const USER_PUBLISH_SUCCESS = "USER_PUBLISH_SUCCESS";
export const USER_PUBLISH_FAIL = "USER_PUBLISH_FAIL";



export const USER_PHOTO_UPDATE_REQUEST = "USER_PHOTO_UPDATE_REQUEST";
export const USER_PHOTO_UPDATE_SUCCESS = "USER_PHOTO_UPDATE_SUCCESS";
export const USER_PHOTO_UPDATE_FAIL = "USER_PHOTO_UPDATE_FAIL";

export const USER_PHOTO_UPLOAD_REQUEST = "USER_PHOTO_UPLOAD_REQUEST";
export const USER_PHOTO_UPLOAD_SUCCESS = "USER_PHOTO_UPLOAD_SUCCESS";
export const USER_PHOTO_UPLOAD_FAIL = "USER_PHOTO_UPLOAD_FAIL";


export const EDIT_PROFILE_DATA_REQUEST = "EDIT_PROFILE_DATA_REQUEST";
export const EDIT_PROFILE_DATA_SUCCESS = "EDIT_PROFILE_DATA_SUCCESS";
export const EDIT_PROFILE_DATA_FAIL = "EDIT_PROFILE_DATA_FAIL";


